### ISSUE TITLE
Can't Lift IO through ReadlineC

### ISSUE THREAD

**Issue by remexre** [fused-effects/fused-effects-readline#3]
This might not be possible unless/until InputT gets MonadBaseControl?

**Comment by robrix** [comment]
Yeah, might not be able to do much better than `MonadIO` for the time being. In particular, it looks like `haskeline` doesn’t export the constructor for `InputT`.

It would definitely be nice to support this.

**Comment by robrix** [comment]
Heads up that this is fixed on `master` so long as you’re able to use `haskeline` 0.8.1 or more recent.
